excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://MaheshTK.github.io
title: Productivity tools
tagline: A journey towards effient workflows
description: A journey towards effient workflows
paginate: 5
